-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.letco_user
(
    id serial NOT NULL,
    name character varying(50) NOT NULL,
    pseudo character varying(50),
    email character varying(50) NOT NULL,
    password character varying(50) NOT NULL,
    bluetooth character varying(50) NOT NULL,
    idrole integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.letco_role
(
    id serial NOT NULL,
    type character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.letco_competence
(
    id serial NOT NULL,
    type character varying(50) NOT NULL,
    description character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_search
(
    id serial NOT NULL,
    iduser integer NOT NULL,
    idcompetence integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_competence
(
    id serial NOT NULL,
    iduser integer NOT NULL,
    idcompetence integer NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.letco_user
    ADD FOREIGN KEY (idrole)
    REFERENCES public.letco_role (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_search
    ADD FOREIGN KEY (iduser)
    REFERENCES public.letco_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_search
    ADD FOREIGN KEY (idcompetence)
    REFERENCES public.letco_competence (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_competence
    ADD FOREIGN KEY (iduser)
    REFERENCES public.letco_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_competence
    ADD FOREIGN KEY (idcompetence)
    REFERENCES public.letco_competence (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;